from genieutils.task import Task

healing = [
    Task(task_type=1, id=12, is_default=0, action_type=155, class_id=0, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=45.0, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=109.0, enable_targeting=0, combat_level_flag=6, gather_type=21, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89026, wwise_resource_deposit_sound_id=89026), 
    Task(task_type=1, id=13, is_default=0, action_type=155, class_id=4, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=45.0, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=109.0, enable_targeting=0, combat_level_flag=6, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89026, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=14, is_default=0, action_type=155, class_id=6, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=45.0, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=109.0, enable_targeting=0, combat_level_flag=6, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89026, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=15, is_default=0, action_type=155, class_id=12, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=45.0, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=109.0, enable_targeting=0, combat_level_flag=6, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89026, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=16, is_default=0, action_type=155, class_id=18, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=45.0, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=109.0, enable_targeting=0, combat_level_flag=6, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89026, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=17, is_default=0, action_type=155, class_id=19, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=45.0, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=109.0, enable_targeting=0, combat_level_flag=6, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89026, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=18, is_default=0, action_type=155, class_id=23, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=45.0, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=109.0, enable_targeting=0, combat_level_flag=6, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89026, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=19, is_default=0, action_type=155, class_id=35, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=45.0, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=109.0, enable_targeting=0, combat_level_flag=6, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89026, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=20, is_default=0, action_type=155, class_id=36, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=45.0, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=109.0, enable_targeting=0, combat_level_flag=6, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89026, wwise_resource_deposit_sound_id=0)
    ]

attackSpeed = [
    Task(task_type=1, id=5, is_default=0, action_type=155, class_id=0, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=0.08695650100708008, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=10.0, enable_targeting=0, combat_level_flag=39, gather_type=22, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89024, wwise_resource_deposit_sound_id=89024), 
    Task(task_type=1, id=6, is_default=0, action_type=155, class_id=6, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=0.08695650100708008, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=10.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89024, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=7, is_default=0, action_type=155, class_id=12, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=0.08695650100708008, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=10.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89024, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=8, is_default=0, action_type=155, class_id=23, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=0.08695650100708008, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=10.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89024, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=9, is_default=0, action_type=155, class_id=35, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=0.08695650100708008, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=10.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89024, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=10, is_default=0, action_type=155, class_id=36, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=0.08695650100708008, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=10.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89024, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=11, is_default=0, action_type=155, class_id=44, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=0.08695650100708008, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=10.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89024, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=12, is_default=0, action_type=155, class_id=47, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=0.08695650100708008, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=10.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89024, wwise_resource_deposit_sound_id=0)
    ]

movementSpeed = [
    Task(task_type=1, id=5, is_default=0, action_type=155, class_id=0, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=1.149999976158142, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=5.0, enable_targeting=0, combat_level_flag=39, gather_type=23, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89032, wwise_resource_deposit_sound_id=89032), 
    Task(task_type=1, id=6, is_default=0, action_type=155, class_id=6, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=1.149999976158142, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=5.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89032, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=7, is_default=0, action_type=155, class_id=12, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=1.149999976158142, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=5.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89032, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=8, is_default=0, action_type=155, class_id=23, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=1.149999976158142, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=5.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89032, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=9, is_default=0, action_type=155, class_id=35, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=1.149999976158142, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=5.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89032, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=10, is_default=0, action_type=155, class_id=36, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=1.149999976158142, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=5.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89032, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=11, is_default=0, action_type=155, class_id=44, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=1.149999976158142, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=5.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89032, wwise_resource_deposit_sound_id=0), 
    Task(task_type=1, id=12, is_default=0, action_type=155, class_id=47, unit_id=-1, terrain_id=-1, resource_in=-1, resource_multiplier=-1, resource_out=-1, unused_resource=-1, work_value_1=1.149999976158142, work_value_2=1.0, work_range=10.0, auto_search_targets=0, search_wait_time=5.0, enable_targeting=0, combat_level_flag=3, gather_type=0, work_flag_2=0, target_diplomacy=1, carry_check=0, pick_for_construction=0, moving_graphic_id=-1, proceeding_graphic_id=-1, working_graphic_id=-1, carrying_graphic_id=-1, resource_gathering_sound_id=-1, resource_deposit_sound_id=-1, wwise_resource_gathering_sound_id=89032, wwise_resource_deposit_sound_id=0)
    ]

